
# Imagen base de Node.js para ejecutar json-server.
FROM node:24-alpine

# Define la carpeta de trabajo dentro del contenedor.
WORKDIR /app

# Instala json-server de forma global dentro del contenedor.
RUN npm install -g json-server@0.17.4

# Copia el archivo db.json al contenedor.
COPY db.json .

# Expone el puerto interno 3000.
EXPOSE 3000

# Ejecuta json-server observando el archivo db.json.
# --host 0.0.0.0 permite que el servicio sea accesible desde fuera del contenedor.
CMD ["json-server", "--watch", "db.json", "--host", "0.0.0.0", "--port", "3000"]
