
server {
    # Puerto interno donde NGINX atenderá las solicitudes.
    listen 80;

    # Carpeta donde estarán los archivos compilados de Angular.
    root /usr/share/nginx/html;

    # Archivo principal de la aplicación.
    index index.html;

    # Configuración principal para una aplicación Angular SPA.
    location / {
        # Primero intenta encontrar el archivo solicitado.
        # Si no existe, redirige hacia index.html.
        # Esto permite que rutas como /preventas-json-server funcionen al recargar.
        try_files $uri $uri/ /index.html;
    }

    # Configuración opcional para archivos estáticos.
    # Permite que CSS, JS, imágenes y fuentes se sirvan correctamente.
    location ~* \.(?:css|js|jpg|jpeg|gif|png|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
    }

    # Página de error interna.
    error_page 500 502 503 504 /50x.html;
}
